// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYhKRWUuKkVuFTb0dbbzueiLKfHLVLKaQ',
    appId: '1:680347791149:web:a50a5655fc716ee2d26da4',
    messagingSenderId: '680347791149',
    projectId: 'lab08-c8567',
    authDomain: 'lab08-c8567.firebaseapp.com',
    storageBucket: 'lab08-c8567.appspot.com',
    measurementId: 'G-3RS1390SGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwdjqH_zYXp6F9yA3kqpRBUA3Q-SXTLn4',
    appId: '1:680347791149:android:81d2b9d79952570ed26da4',
    messagingSenderId: '680347791149',
    projectId: 'lab08-c8567',
    storageBucket: 'lab08-c8567.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN7qSZA4Y1DK86-dOlGt7w1PGSJiqKIW8',
    appId: '1:680347791149:ios:61a3e83f70ba2062d26da4',
    messagingSenderId: '680347791149',
    projectId: 'lab08-c8567',
    storageBucket: 'lab08-c8567.appspot.com',
    iosClientId: '680347791149-nmn37o60psmikufbve8gk1bsplv4o7c3.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab08',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN7qSZA4Y1DK86-dOlGt7w1PGSJiqKIW8',
    appId: '1:680347791149:ios:61a3e83f70ba2062d26da4',
    messagingSenderId: '680347791149',
    projectId: 'lab08-c8567',
    storageBucket: 'lab08-c8567.appspot.com',
    iosClientId: '680347791149-nmn37o60psmikufbve8gk1bsplv4o7c3.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab08',
  );
}
